### ISSUE TITLE
readme: link to demo gif is dead

### ISSUE THREAD

**Issue by zeozeozeo** [chqs-git/code-plus#1]
The gif under [Demonstration](https://github.com/chqs-git/code-plus?tab=readme-ov-file#demonstration) does not load because the original URL (https://s12.gifyu.com/images/Sckre.gif) is dead.

Archived version of the gif: http://web.archive.org/web/20240703131809/https://s12.gifyu.com/images/Sckre.gif
![](http://web.archive.org/web/20240703131809/https://s12.gifyu.com/images/Sckre.gif)

**Comment by zeozeozeo** [comment]
the same gif is also dead in https://github.com/lite-xl/lite-xl-plugins

**Comment by chqs-git** [comment]
Hello,

Thank your for bringing this to my attention. This is quite an old plugin so It seems the link has expired.

Also thank you for the archive! I will update the readme with a new gif link. Have a good day.

**Comment by chqs-git** [comment]
I will leave this open in case there is another issue.

**Comment by zeozeozeo** [comment]
It seems to be dead again xD
perhaps it would be better to put it in the repository and link to it with a path

**Comment by chqs-git** [comment]
Lmao, 
my only concern doing that, is that the media will then be included when people use the package.

I think I can host it in my own drive, I've using gif host websites because I'm too lazy.

Either way thank you again, not really sure when I will be fixing this but I appreciate your help.

**Comment by chqs-git** [comment]
I have hopefully fixed this issue for good by hosting the media on a different repository.

The link is still dead in Lite XL but I'm not worried about it. I will leave this issue open for now in case something new turns up. Thank you.
